bounswe/bounswe2024group11

- .github/ISSUE_TEMPLATE/config.yml
> fix: readded a config file for issue templates

- README.md
> docs: modify readme to catch up with wiki

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request-issue.md
- .github/ISSUE_TEMPLATE/simple-todo-issue.md
- README.md
> fix: remove blank issues from template config

- backend/config/urls.py
Fixing a dummy urlpattern in the project config urls.
> fix: Fix a urlpattern in the config

- web/postcss.config.cjs
- web/tailwind.config.ts
> fix(web): tailwindcss generates class names

- backend/Dockerfile
- backend/docker-compose.yml
The backend application is Dockerized. You can run the application by:
```bash
docker-compose up
```
> feat(backend): Dockerize the backend app

- .vscode/settings.json
- web/src/App.tsx
- web/src/index.css
- web/src/main.tsx
- web/src/theme.ts
> style(web): add design tokens and style configs

- web/src/Login.tsx
See this [discussion](https://github.com/bounswe/bounswe2024group11/discussions/254) for more details.
> feat(web): add aria labels

- backend/Dockerfile
- docker-compose.yml
- web/Dockerfile
- web/package-lock.json
- web/package.json
All the main components of the application are dockerized:
- Database
- Backend
- Frontend
You can try it by running these commands sequentially: 
```bash
docker-compose build
docker-compose up
```
> feat(devops): dockerize the whole application

- mobile/components/CustomInput.tsx
- mobile/components/ProfileHeader.tsx
- mobile/components/SearchHeader.tsx
- mobile/components/StorageHandler.tsx
- mobile/components/Styles.tsx
- mobile/screens/Home.tsx
- mobile/screens/Login.tsx
- mobile/screens/Search.tsx
> feat(mobile): added async and storage methods

- mobile/app.json
- mobile/components/CreatePostButton.tsx
- mobile/components/CustomInput.tsx
- mobile/components/Post.tsx
- mobile/components/SearchHeader.tsx
- mobile/components/StorageHandler.tsx
- mobile/components/Styles.tsx
- mobile/components/Types.tsx
- mobile/screens/CreatePost.tsx
- mobile/screens/Feed.tsx
- mobile/screens/Home.tsx
- mobile/screens/Login.tsx
- mobile/screens/Post.tsx
- mobile/screens/Search.tsx
- mobile/screens/Signup.tsx
> feat(mobile): added create post screen

- mobile/components/Post.tsx
- mobile/components/Styles.tsx
- mobile/package-lock.json
- mobile/screens/CreatePost.tsx
- mobile/screens/Feed.tsx
> feat(mobile): added post component

- docker-compose.yml
- nginx/nginx.conf
- I have created a folder named nginx in the root directory in order to put nginx.conf configuration file where it is mounted to nginx service in the docker-compose build.
- Modified the docker-compose.yml file in a way it builds the nginx service after building web service in a container.
- Any requests to endpoints starting with /api is directed to backend service, if not it is directed to web service where client can interact.
It is important to note that, since the backend api calls are changed with /api/v1 modifier in the beginning, frontend calls are not testable until front end source code will be modified according to new calls to backend.
> feat(devops): added nginx conf file under nginx directory and modified docker-compose.yml.

- mobile/components/CustomOutput.tsx
- mobile/components/ProfileInfo.tsx
- mobile/components/Styles.tsx
- mobile/context/UserContext.tsx
- mobile/package-lock.json
- mobile/package.json
- mobile/screens/Profile.tsx
> feat(mobile): created profile page

- mobile/components/SearchHeader.tsx
- mobile/components/StorageHandler.tsx
- mobile/components/Styles.tsx
- mobile/screens/CreatePost.tsx
- mobile/screens/Search.tsx
> feat(mobile): added suggestion feature in the search bars in the app

- backend2/config/settings.py
- backend2/core/urls.py
- backend2/core/views.py
- backend2/swagger_docs/wikidata_swagger.py
* resolves #383 
* swagger ui is created. can be seen at api/swagger. 
* openapi documentation for SearchPostView and WikidataSuggestionsView are provided
> feat(backend): add swagger ui

- web/src/components/Navbar.tsx
- web/src/components/Post.tsx
- web/src/components/WikiWidget.tsx
- web/src/routes/Home.tsx
> Web wiki widget

- mobile/components/Post.tsx
- mobile/components/StorageHandler.tsx
- mobile/context/UserContext.tsx
- mobile/screens/CreatePost.tsx
- mobile/screens/Feed.tsx
- mobile/screens/Login.tsx
- mobile/screens/Post.tsx
- mobile/screens/Search.tsx
- mobile/screens/Signup.tsx
thanks to @Meminseeker and @yunuskaydin, we've managed to connect the mobile app to the backend. Common work is committed through my profile.
> feat(mobile): connect to backend

- web/src/router.tsx
- web/src/routes/Bookmarks.tsx
- web/src/routes/Home.tsx
- web/src/routes/Profile.data.ts
- web/src/routes/Profile.tsx
- web/src/routes/shadow/profile/Follow.data.ts
- web/src/routes/shadow/profile/Unfollow.data.ts
- web/src/routes/shadow/profile/UpdateBio.data.ts
- web/src/theme.ts
> feat(web): implement conditional profile pages & improve styling and page layouts

- backend/core/serializers.py
- bruno/get users.bru
- bruno/login.bru
- bruno/signup.bru
> fix(backend): add fullname field to user serializers

- backend/core/serializers.py
- backend/core/tests/test_search.py
- backend/core/tests/test_suggestions.py
- backend/core/views.py
- bruno/get users.bru
- bruno/login.bru
- bruno/signup.bru
> test(backend): add unit tests for search and suggestions

- backend/core/serializers.py
- bruno/follow.bru
- bruno/get all users.bru
- bruno/search posts.bru
> feat(backend): add is_follower field to ProfileSerializer and SearchPostSerializer

- mobile/App.tsx
- mobile/app/context/AuthContext.tsx
- mobile/app/screens/Home.tsx
- mobile/app/screens/Login.tsx
This PR adds auth context with these details:
- feat(mobile): add AuthContext for authentication
- feat(mobile): add AuthProvider and navigation stack in App.tsx
- feat(mobile): add Login screen
- feat(mobile): add dummy Home screen
Resolves #525
> feat(mobile): add auth context

- mobile/db.json
- mobile/package-lock.json
- mobile/package.json
Adds json-server for:
1. Forum feed
2. Detail pages of forum questions
Closes #544
> chore(mobile): implement mock server for forum pages

- backend/config/settings.py
- backend/core/tests/test_forum_question.py
- backend/core/views/forum_views.py
Co-authored-by: MucahitErdoganUnlu mucahit.719@hotmail.com
Related to: #556
> feat(be): Add pagination for Forum Questions

- mobile/App.tsx
- mobile/app/components/AuthorView.tsx
- mobile/app/components/BookmarkButton.tsx
- mobile/app/components/ForumAnswerCard.tsx
- mobile/app/components/ForumQuestionCard.tsx
- mobile/app/components/VoteButtonsView.tsx
- mobile/app/context/AuthContext.tsx
- mobile/app/screens/Forum.tsx
- mobile/app/screens/ForumQuestionDetail.tsx
- mobile/app/screens/Home.tsx
- mobile/app/screens/Login.tsx
- mobile/app/types/forum.ts
- mobile/app/utils.tsx
- mobile/package-lock.json
- mobile/package.json
1. Adds prettier as a dev dependency
2. Refactor .ts and .tsx project files inside mobile directory
> chore(mobile): add prettier as a dev dependency for mobile application

- .github/ISSUE_TEMPLATE/modelviewset-issue.md
> feat(be): create an issue template for implementing model and modelviewset for django rest

- backend/.env.example
- backend/core/urls.py
- backend/core/views/get_translation_views.py
> feat(be): implement get translation endpoint

- backend/core/urls.py
- backend/core/views/hint_views.py
> feat(backend): implement hint mechanism for quiz question

- mobile/app/components/VoteButtonsView.tsx
- mobile/app/screens/ForumQuestionDetail.tsx
- mobile/app/types/forum.ts
Adds create answer on forumQuestionDetail screen.
> feat(mobile): implement create answer mechanism

- client/src/components/forum-card.tsx
- client/src/components/quiz-card.tsx
- client/src/router.tsx
- client/src/routes/Forum/Forum.data.tsx
- client/src/routes/Forum/Forum.tsx
- client/src/routes/Forum/NewForum.tsx
- client/src/routes/Forum/Question.tsx
- client/src/routes/Forum/RelevantQuizQuestion.tsx
- client/src/routes/Quiz/Quiz.Review.tsx
- client/src/routes/Quiz/Quiz.data.tsx
- client/src/routes/Quiz/Quiz.schema.ts
- client/src/routes/Quiz/Quiz.tsx
- client/src/routes/Quiz/Quizzes.data.tsx
- client/src/routes/Quiz/Quizzes.tsx
- client/src/store.ts
closes #688 
closes #703 
closes #695 
closes #697
> feat(client): implement quiz review

- backend/core/tests/test_get_translation.py
> feat(be): implement unittests for get_translation endpoint

- README.md
Main Topics To Discuss & Document:
- Primary features
- Domain-specific features
- API and its documentation
- Standard(s) being followed
- Testing strategies
> lab: checklist items for lab8

- backend/core/serializers/forum_question_serializer.py
- backend/core/utils.py
- backend/core/views/forum_views.py
- backend/core/views/semantic_search_views.py
> feat(be): semantically relate a forum question to other forum questions

- backend/core/urls.py
- backend/core/views/interest_views.py
Implemented CD endpoints for interests  and swagger documentation.
resolves #767
> feat(be): implement CD endpoints for interest

- backend/config/settings.py
- backend/core/achievements/conditions.py
- backend/core/achievements/services.py
- backend/core/middleware.py
- backend/core/serializers/achievement.py
- backend/core/serializers/profile_serializer.py
> feat(be): implement achievements notification

- mobile/App.tsx
- mobile/app/components/DeleteAnswerButton.tsx
- mobile/app/components/EditAnswerButton.tsx
- mobile/app/components/ForumAnswerCard.tsx
- mobile/app/screens/EditAnswer.tsx
- mobile/app/screens/ForumQuestionDetail.tsx
- mobile/app/types/forum.ts
adds delete button for forum answers.
adds edit button for forum answers.
closes #806.
> feat(mobile): add delete and edit button to forum answers

- client/src/components/command-menu.tsx
- client/src/components/info-box.tsx
- client/src/components/tagselect.tsx
- client/src/contexts/CommandMenuContext.tsx
- client/src/contexts/SoundContext.tsx
- client/src/contexts/speechContext.tsx
- client/src/hooks/command-menu.ts
- client/src/hooks/pagination.ts
- client/src/hooks/useSpeech.ts
- client/src/main.tsx
- client/src/routes/Home/Home.main.tsx
- client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptions.tsx
- client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptionsHint.tsx
- client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptionsHintCustom.tsx
- client/src/routes/Quiz/NewQuiz/WordSelectionView.tsx
- client/src/routes/Quiz/NewQuiz/state.ts
- client/src/routes/Quiz/QuizChoice.tsx
- client/src/routes/_root.tsx
closes #731 
https://github.com/user-attachments/assets/a16498ba-33c1-4ee0-bdf9-ac4af70b0492
> ux(client): `(cmd+K)` command menu to access navigation and actions

- backend/core/views/achievement_views.py
- client/src/components/navbar.tsx
- client/src/routes/Auth/Register.tsx
- client/src/routes/Forum/NewForum.tsx
- client/src/routes/Home/Home.data.tsx
- client/src/routes/Home/Home.tsx
- client/src/routes/_loading.tsx
> feat(client): add proficiency selection to register

- client/pnpm-lock.yaml
- client/src/routes/Forum/NewForum.tsx
- client/src/routes/Forum/NewForumHead.tsx
- client/src/routes/Home/Home.EmptyInterest.tsx
- client/src/routes/Home/Home.tsx
- client/src/routes/Profile/Profile.data.tsx
- client/src/routes/Profile/Profile.tsx
- client/src/routes/Quiz/NewQuiz/NewQuiz.tsx
- client/src/routes/Quiz/NewQuiz/NewQuizHead.tsx
- client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptions.tsx
- client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptionsHint.tsx
> feat(client): add block unblock follow unfollow toast notification

- client/src/components/blockings-modal.tsx
- client/src/components/quiz-card.tsx
- client/src/components/tag-search.tsx
- client/src/components/user-card.tsx
- client/src/routes/Home/HomeAddInterest.tsx
- client/src/routes/Home/HomePeopleSuggestions.tsx
- client/src/routes/Profile/Profile.tsx
> feat(client): display follower and following count on profile

- backend/core/views/feed_views.py
- client/src/router.tsx
- client/src/routes/Profile/ProficiencyChange.tsx
- client/src/routes/Profile/Profile.data.tsx
- client/src/routes/Profile/Profile.schema.ts
- client/src/routes/Profile/Profile.tsx
> feat(client): update proficiency from user profile

- client/pnpm-lock.yaml
- client/src/routes/Auth/Register.tsx
- client/src/routes/Forum/NewForum.tsx
…ion is completed when they are clicked
> feat(client): indicate loading states on actions with photo upload

- backend/core/achievements/conditions.py
- backend/core/utils.py
- client/src/router.tsx
- client/src/routes/Forum/Forum.data.tsx
- client/src/routes/Forum/Forum.tsx
- client/src/routes/Quiz/Quiz.data.tsx
- client/src/routes/Quiz/Quizzes.data.tsx
- client/src/routes/Quiz/Quizzes.tsx
> feat(client): server-side sorting on forum and quizzes

- client/src/router.tsx
- client/src/routes/Forum/Forum.tsx
- client/src/routes/Home/Home.tsx
- client/src/routes/Quiz/Quizzes.tsx
- client/src/routes/_loading.tsx
> refactor(client): improve loading states on home forum and quizzes
